### ISSUE TITLE
Exception processing 2SRC

### ISSUE THREAD

**Issue by skodapetr** [siret/p2rank-web#15]
```
09/09/2020 07:37:55 [DEBUG] - Executing 'cd /opt/conservation/jense_shannon_divergence/ && 
python2 score_conservation.py /data/p2rank/task/database/v2-conservation/2SRC/working/conservation-A/msa > /data/p2rank/task/database/v2-conservation/2SRC/working/conservation-A/structure_A.score'
Traceback (most recent call last):
File "score_conservation.py", line 831, in <module>
seq_weights = load_sequence_weights(align_file.replace('.%s' % align_suffix, '.weights'))
File "score_conservation.py", line 599, in load_sequence_weights
seq_weights.append(float(l[1]))
ValueError: could not convert string to float: A
Traceback (most recent call last):
File "/opt/p2rank-runtime/execute_p2rank.py", line 359, in <module>
main(_read_arguments())
File "/opt/p2rank-runtime/execute_p2rank.py", line 65, in main
structure_file, chains, configuration, arguments)
File "/opt/p2rank-runtime/execute_p2rank.py", line 190, in prepare_conservation
return compute_from_structure(structure_file, chains, arguments)
File "/opt/p2rank-runtime/execute_p2rank.py", line 236, in compute_from_structure
for chain in chains
File "/opt/p2rank-runtime/execute_p2rank.py", line 236, in <dictcomp>
for chain in chains
File "/opt/p2rank-runtime/execute_p2rank.py", line 255, in compute_from_structure_for_chain
conservation.compute_conservation(fasta_file, working_dir, target_file)
File "/opt/p2rank-runtime/conservation.py", line 58, in compute_conservation
compute_jensen_shannon_divergence(msa_file, output_file)
File "/opt/p2rank-runtime/conservation.py", line 257, in compute_jensen_shannon_divergence
execute_command(cmd)
File "/opt/p2rank-runtime/execute_p2rank.py", line 170, in execute_command
result.check_returncode()
File "/usr/lib/python3.7/subprocess.py", line 428, in check_returncode
self.stderr)
subprocess.CalledProcessError: Command 'cd /opt/conservation/jense_shannon_divergence/ && python2 score_conservation.py /data/p2rank/task/database/v2-conservation/2SRC/working/conservation-A/msa > /data/p2rank/task/database/v2-conservation/2SRC/working/conservation-A/structure_A.score' returned non-zero exit status 1.
```

**Comment by skodapetr** [comment]
The reason for this exception is in ```score_conservation.py```:
```
if line[0] != '#' and len(l) == 2:
  seq_weights.append(float(l[1]))
```
